site_name: PubMonkey
# theme:
#   name: gitbook
theme:
    name: mkdocs
    nav_style: dark
    navigation_depth: 0
nav:
  - Home: index.md
  - Release Notes: changelog.md
  - Order Management: order-actions.md
  - Connect GAM: connecting-to-google-ad-manager.md
plugins: []